### ISSUE TITLE
El camp motiuDeFirma ha de ser obligatori quan es petició amb AutoFirma

### ISSUE THREAD

**Issue by ptrias-fundaciobit** [GovernIB/enviafib#296]
El camp motiuDeFirma ha de ser obligatori quan es petició amb AutoFirma:

2023-05-03 12:46:23,153 ERROR [es.caib.enviafib.back.controller.user.AutoFirmaUserController] (default task-17) Error cridant a PortaFIB per a la signatura immediata: org.fundaciobit.apisib.core.exceptions.ApisIBServerException: {CA_.fileInfoSignatureArray.reason}(fileInfoSignatureArray.reason): El camp fileInfoSignatureArray.reason és obligatori.
at deployment.enviafib.ear//org.fundaciobit.apisib.jerseycore.AbstractApisIBConnectionManagerJersey.processException(AbstractApisIBConnectionManagerJersey.java:208)
at deployment.enviafib.ear//org.fundaciobit.apisib.jerseycore.AbstractApisIBConnectionManagerJersey.commonCall(AbstractApisIBConnectionManagerJersey.java:193)
at deployment.enviafib.ear//org.fundaciobit.apisib.apifirmasimple.v1.jersey.ApiFirmaWebSimpleJersey.startTransaction(ApiFirmaWebSimpleJersey.java:110)
at deployment.enviafib.ear.enviafib-back.war//es.caib.enviafib.back.controller.user.AutoFirmaUserController.autofirma(AutoFirmaUserController.java:354)
at deployment.enviafib.ear.enviafib-back.war//es.caib.enviafib.back.controller.user.AutoFirmaUserController.create(AutoFirmaUserController.java:90)
at deployment.enviafib.ear.enviafib-back.war//es.caib.enviafib.back.controller.webdb.PeticioController.crearPeticioPost(PeticioController.java:492)
at deployment.enviafib.ear.enviafib-back.war//es.caib.enviafib.back.controller.user.AbstractFirmaUserController.crearPeticioPost(AbstractFirmaUserController.java:520)

**Comment by ptrias-fundaciobit** [comment]
Fet!
![image](https://user-images.githubusercontent.com/95921330/236208161-62b214ef-9917-4009-b369-a505f1acc2e8.png)
